AllCops:
  NewCops: enable
  SuggestExtensions: false
Lint/DuplicateMethods:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false # Only used in rspec
Metrics/BlockLength:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
